midtermcastana/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

post/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
     path('', views.index, name='index'),
     path('help/', views.help, name='help'),
     path('<int:post_id>/', views.detail ,name='detail'),
     path('<int:post>/update', views.update ,name='update'),
     path('create/', views.create ,name='create')

]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    post_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    pub_date_update = models.DateTimeField('date published',null=True, blank=True)
    content = models.TextField(null=True)



    def __str__ (self):
        return 'Post : {}'.format(self.question_text)


class Comment(models.Model):
    post = models.ForeignKey(Post,
                on_delete=models.CASCADE,
                related_name='comments')
    comment_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

post/forms.py
from django.forms import ModelForm
from .models import Question

class PostModelForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

class Comment(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . models import Post
from . forms import PostModelForm
from . forms import PostDefinitionForm
from django.utils import timezone

# Create your views here.

def index(request):
    context = {}
    posts = Post.objects.all()
    context['Posts'] = posts
    return render(request, 'index.html', context)

def help(request):
        return render('TABANG')


def detail(request, post_id):
    context = {}
    context['post'] = Post.objects.get(id=post_id)
    return render(request, 'detail.html', context)

def update(request,post_id):
    if request.method == 'POST':
         pass
    else:
        post = Post.objects.get(id=post_id)
        context = {}
        context['form'] = PostModelForm(instance=post)
        context['p_id'] = post_id
        return render(request, 'update.html', context)


def create(request):
    context = {}
    form = PostDefinitionForm(initial={"pub_date":timezone.now()})

    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('polls:index')

    return render(request, "create.html", {'form':form})

def comment(request):
    context = {}
    

# Create your views here.

post/templates/base.html
{% load static %}


<html>


  <head>

    <title>
      {% block head %}
          this is the title head
      {% endblock %}

    </title>
    <link rel ="stylesheet" type ="text/css" href="{% static 'post/materialize/css/materialize.min.css' %}">
    {% block sheets %}
    {% endblock %}
  </head>



  <body>
    {% block body %}
      12345
    {% endblock %}
    <script src = "{% static 'post/materialize/js/materialize.min.js' %}"></script>
  </body>

    {% block script %}
    {% endblock %}




</html>

post/templates/create.html
{% extends 'base.html' %}
 {% block head %}
 this is the update page
  {% endblock %}
   {% block body %}
   <form action="{% url 'polls:create' %}" method="POST">
    {% csrf_token %}
    {% for field in form %}
      {{ field.errors }}
      {{ field.label }} {{ field }}
    {% endfor %}
      <input type="submit" value="Create">
    </form>
      {% endblock %}

post/templates/detail.html
{% extends 'base.html' %}
{% block head %}



this is the detail page {% endblock %}


 {% block body %}


 {{ post.post_text }}<br />
  {{ post.pub_date }}<br/>


  {% for comment in post.comments.all %}
  {{ comment.comment_text }} | votes: {{ comment.votes }} <br/>


   {% endfor %}
   {% endblock %}

post/templates/index.html
{% extends 'base.html' %}


{% block head %}
  this is the index page
{% endblock %}



{% block body %}

  <ol>
  {% for post in posts %}
   <li>
   <a href ="{% url 'posts:detail' post.id %} "> Post : {{ post.post_text }}  <br /> </a>

   </li>
    {% endfor %}
  </ol>

{% endblock %}

post/templates/update.html
{% extends 'base.html' %}
 {% block head %}
 this is the update page
  {% endblock %}
   {% block body %}
   <form action="{% url 'post:update' p_id %}" method="POST">
    {% csrf_token %}
    {% for field in form %}
      {{ field.errors }}
      {{ field.label }} {{ field }}
    {% endfor %}
      <input type="submit" value="Update">
    </form>
      {% endblock %}